forge "http://forge.puppetlabs.com"

mod 'puppetlabs/stdlib'
mod 'puppetlabs/apt'
mod 'puppetlabs/ruby'
mod 'puppetlabs/vcsrepo'

# mod 'ntp',
#   :git => 'git://github.com/puppetlabs/puppetlabs-ntp.git'

# mod 'apt',
#    :git => 'https://github.com/puppetlabs/puppetlabs-apt.git',
#    :ref => 'feature/master/dans_refactor'

# mod "apt",
#  :git => "git://github.com/puppetlabs/puppetlabs-apt.git"

# mod "stdlib",
#  :git => "git://github.com/puppetlabs/puppetlabs-stdlib.git"